x-environment: &default-environment
  DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@glitchtip-postgres:5432/postgres
  SECRET_KEY: ${SECRET_KEY:-change_me_to_something_random}  # best to run openssl rand -hex 32
  PORT: 8000  # If changing, change the web service port too
  EMAIL_URL: ${EMAIL_URL:-consolemail://}  # Example smtp://email:password@smtp_url:port
  GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN:-http://localhost}  # Change this to your domain
  CSRF_TRUSTED_ORIGINS: ${GLITCHTIP_DOMAIN:-http://localhost}
  CORS_ALLOWED_ORIGINS: ${GLITCHTIP_DOMAIN:-http://localhost}
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL:-email@example.com}  # Change this to your email
  REDIS_URL: redis://${REDIS_PASSWORD:+:${REDIS_PASSWORD}@}glitchtip-valkey:6379/0
  CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://${REDIS_PASSWORD:+:${REDIS_PASSWORD}@}glitchtip-valkey:6379/0}
  CACHE_URL: ${CACHE_URL:-redis://${REDIS_PASSWORD:+:${REDIS_PASSWORD}@}glitchtip-valkey:6379/0}
  CELERY_WORKER_AUTOSCALE: 1,3
  GLITCHTIP_MAX_EVENT_LIFE_DAYS: ${GLITCHTIP_MAX_EVENT_LIFE_DAYS:-14}
  GLITCHTIP_MAX_TRANSACTION_EVENT_LIFE_DAYS: ${GLITCHTIP_MAX_TRANSACTION_EVENT_LIFE_DAYS:-${GLITCHTIP_MAX_EVENT_LIFE_DAYS:-14}}
  GLITCHTIP_MAX_FILE_LIFE_DAYS: ${GLITCHTIP_MAX_FILE_LIFE_DAYS:-$${GLITCHTIP_MAX_EVENT_LIFE_DAYS:-14}}
  ENABLE_USER_REGISTRATION: ${ENABLE_USER_REGISTRATION:-False}
  ENABLE_ORGANIZATION_CREATION: ${ENABLE_ORGANIZATION_CREATION:-False}
  UWSGI_WORKERS: ${UWSGI_WORKERS:-2}
  UWSGI_CHEAPER: ${UWSGI_CHEAPER:-1}
  UWSGI_CHEAPER_INITIAL: ${UWSGI_CHEAPER_INITIAL:-1}
  CELERY_WORKER_CONCURRENCY: ${CELERY_WORKER_CONCURRENCY:-2}

x-depends_on: &default-depends_on
  - glitchtip-postgres
  - glitchtip-valkey

x-healthcheck-postgres: &postgres-healthcheck
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

x-logging: &json-logging
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "10"

x-glitchtip-base: &glitchtip-base
  image: glitchtip/glitchtip:v4.2.5
  depends_on: *default-depends_on
  environment: *default-environment
  restart: unless-stopped
  volumes:
    - glitchtip-uploads:/code/uploads
  <<: *json-logging

services:
  glitchtip-postgres:
    image: postgres:17
    container_name: glitchtip-postgres
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    restart: unless-stopped
    volumes:
      - glitchtip-postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G

  glitchtip-valkey:
    image: valkey/valkey:latest
    container_name: glitchtip-valkey
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - glitchtip-redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

  glitchtip-web:
    <<: *glitchtip-base
    container_name: glitchtip-web
    deploy:
      resources:
        limits:
          memory: 1G

  glitchtip-worker:
    <<: *glitchtip-base
    container_name: glitchtip-worker
    command: ./bin/run-celery-with-beat.sh
    deploy:
      resources:
        limits:
          memory: 1G

  glitchtip-nginx:
    image: nginx:alpine
    container_name: glitchtip-nginx
    restart: unless-stopped
    ports:
      - "${EXTERNAL_PORT:-80}:80"
      - "${EXTERNAL_SSL_PORT:-443}:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - glitchtip-web
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  glitchtip-migrate:
    <<: *glitchtip-base
    container_name: glitchtip-migrate
    command: ./bin/run-migrate.sh
    restart: "no"
    depends_on:
      glitchtip-postgres:
        condition: service_healthy

volumes:
  glitchtip-postgres-data:
    name: glitchtip-postgres-data
  glitchtip-uploads:
    name: glitchtip-uploads
  glitchtip-redis-data:
    name: glitchtip-redis-data